# -*- coding: utf-8 -*-
"""교재 기반 AI 토픽 데이터.

Source: 04. 인공지능 for 기본반_v1.1_.pdf (최우슬 PE, 197p)
"""

PAST_EXAMS = [
    ("135", "컴시응", "Monte Carlo Tree Search (MCTS)"),
    ("135", "컴시응", "차원의 저주 (Curse of Dimensionality)"),
    ("135", "컴시응", "RAG (Retrieval-Augmented Generation)"),
    ("135", "컴시응", "생성형 AI 멀티모달 데이터 품질검증 (TTAK.KO-10.1558)"),
    ("135", "관리", "PR 곡선 vs ROC 곡선 비교"),
    ("135", "관리", "Multimodal LLM"),
    ("135", "관리", "실루엣 계수 (Silhouette Coefficient)"),
    ("135", "관리", "불편추정량 (Unbiased Estimator)"),
    ("135", "관리", "VAE (Variational Autoencoder)"),
    ("135", "관리", "AGI 관점에서 ANI의 필요성"),
    ("135", "관리", "회귀모형 — 등분산성·다중공선성"),
    ("135", "관리", "LLM 적용 5가지 고려사항·5가지 아키텍처"),
    ("135", "관리", "프롬프트 엔지니어링 기술요소·활용방안"),
    ("135", "관리", "딥페이크 — 개념·핵심기술·문제점·대응방안"),
    ("135", "관리", "이항분포 vs 포아송분포"),
    ("135", "관리", "빅데이터 시각화"),
    ("135", "관리", "AI SW 품질보증 테스트 (Metamorphic, Neuron Coverage, 안전반경)"),
    ("134", "컴시응", "온디바이스 AI"),
    ("134", "컴시응", "공공부문 초거대 AI 도입·활용 가이드라인"),
    ("134", "컴시응", "멀티모달 인공지능"),
    ("134", "관리", "ML 성능지표"),
    ("134", "관리", "이미지 데이터 어노테이션"),
    ("134", "관리", "RAG"),
    ("134", "관리", "AI 법적·윤리·기술 이슈와 해결방안"),
    ("134", "관리", "SOM (Self Organizing Map)"),
    ("133", "관리", "AI 신뢰성 개념·핵심속성"),
    ("133", "관리", "딥페이크"),
    ("133", "관리", "PLM → LLM 훈련 과정"),
    ("133", "관리", "생성형 AI 보안위협·대응 (챗GPT 보안가이드라인)"),
    ("133", "관리", "인공신경망 — FFNN·역전파·활성화함수"),
    ("132", "관리", "베이지안 최적화"),
    ("132", "관리", "다중공선성"),
    ("132", "관리", "중심극한정리·t-검정·z-검정"),
    ("132", "관리", "선형 SVM 마진 분류 2가지"),
    ("132", "관리", "TF-IDF 계산"),
    ("132", "관리", "LangChain + LLM 설비예지정비"),
    ("132", "컴시응", "파인튜닝 (Fine-tuning)"),
    ("132", "컴시응", "SVM 개념·동작·장단점"),
    ("131", "관리", "데이터 차원축소"),
    ("131", "관리", "ML vs DL 차이"),
    ("131", "관리", "독립표본 t-검정 vs 대응표본 t-검정"),
    ("131", "관리", "AI 윤리·거버넌스 모형"),
    ("131", "관리", "AI 학습용 데이터 허브·품질관리"),
    ("131", "관리", "Foundation Model"),
    ("131", "컴시응", "Monte Carlo Method"),
    ("131", "컴시응", "Autoencoder"),
    ("131", "컴시응", "전이학습 (Transfer Learning)"),
    ("131", "컴시응", "MDP·벨만방정식·강화학습"),
    ("131", "컴시응", "추천시스템 (CBF·CF·행렬분해)"),
    ("130", "관리", "ML 최적화 알고리즘"),
    ("130", "관리", "K-means·DBSCAN·SVM"),
    ("130", "관리", "DSML·MLOps"),
    ("130", "관리", "의사결정나무"),
    ("130", "관리", "적대적 공격·생성형 AI 보안취약점"),
    ("129", "관리", "AI 윤리 3대 원칙·10대 요건"),
    ("129", "관리", "K-Means vs DBSCAN"),
    ("129", "관리", "딥뷰 (DeepView)"),
    ("129", "관리", "데이터마이닝 vs 통계·오피니언마이닝"),
    ("129", "컴시응", "튜링 테스트"),
    ("129", "컴시응", "벤치마크 데이터셋"),
    ("128", "관리", "ModelOps"),
    ("128", "관리", "상관관계 vs 인과관계"),
    ("128", "관리", "뉴로모픽 칩"),
    ("128", "관리", "AI 학습용 데이터 품질관리 가이드라인"),
    ("128", "관리", "데이터3법·마이데이터"),
    ("128", "관리", "연합학습 (Federated Learning)"),
    ("128", "컴시응", "CNN 계층"),
    ("128", "컴시응", "유사도 (Jaccard·Cosine·Silhouette)"),
    ("128", "컴시응", "AIaaS"),
    ("128", "컴시응", "교차검증"),
    ("128", "컴시응", "엣지컴퓨팅"),
    ("127", "관리", "ModelOps"),
    ("127", "관리", "과적합 원인·해결"),
    ("127", "관리", "온디바이스 AI"),
    ("126", "관리", "앙상블 Bagging vs Boosting"),
    ("126", "관리", "AI 학습용 빅데이터·라벨링"),
    ("126", "컴시응", "결측값 처리"),
    ("126", "컴시응", "YOLO 얼굴검출"),
    ("120", "관리", "앙상블 기법"),
    ("120", "관리", "파라미터 vs 하이퍼파라미터·튜닝"),
    ("120", "컴시응", "RNN"),
    ("120", "컴시응", "선형회귀 vs 로지스틱회귀"),
    ("119", "관리", "Gradient Descent"),
    ("119", "컴시응", "SVM"),
    ("119", "컴시응", "역전파"),
    ("114", "관리", "Q-Learning"),
    ("114", "컴시응", "강화학습"),
    ("113", "관리", "MCTS"),
    ("113", "관리", "퍼셉트론·XOR 한계"),
    ("113", "관리", "유전알고리즘"),
    ("111", "관리", "HMM"),
    ("111", "관리", "혼동행렬·성능평가"),
    ("110", "관리", "Random Forest"),
    ("110", "관리", "AI 법제도 촉진·규제"),
    ("108", "관리", "AI 특이점·엑소브레인·딥뷰"),
    ("117", "관리", "XAI"),
    ("117", "관리", "AI 편향(bias) 원인"),
    ("116", "관리", "F1·Precision·Recall"),
]

MNEMONICS = [
    ("1. AI 분류", "약강초", "약(ANI) · 강(AGI) · 초(ASI)", "지적수준별 AI 분류. 기출 ANI 필요성.", "overview-1"),
    ("1. AI 윤리", "인공기", "인(간존엄) · 공(공선) · 기(합목적)", "정부 AI 윤리 3대 기본원칙.", "overview-3"),
    ("1. AI 윤리10", "인프다침공연책안투", "인권·프라이버시·다양성·침해금지·공공성·연대·데이터·책임·안전·투명", "10대 핵심요건.", "overview-3"),
    ("2. ML 분류", "지비강", "지(도) · 비(지도) · 강(화)", "학습 유형 3분류.", "ml-0"),
    ("2. 지도학습", "분회", "분(류) · 회(귀)", "Classification vs Regression.", "ml-1"),
    ("2. 비지도", "군차연", "군(집) · 차(원축소) · 연(관규칙)", "Clustering·PCA·Association.", "ml-2"),
    ("3. K-means", "K-중심-반복", "K개 중심 → 할당 → 재계산", "군집화 대표 알고리즘.", "cluster-0"),
    ("3. DBSCAN", "밀도-코어-보더", "ε·MinPts → Core/Border/Noise", "밀도 기반 군집.", "cluster-1"),
    ("4. PCA", "공분산-고유값-주성분", "분산 최대 방향 투영", "차원축소 핵심.", "dim-0"),
    ("5. Apriori", "지지-신뢰-향상", "Support·Confidence·Lift", "연관규칙 3지표.", "assoc-0"),
    ("6. DT", "지니-엔트로피", "불순도 최소 분할", "의사결정나무 분할 기준.", "class-0"),
    ("6. SVM", "마진-서포트", "최대 마진 초평면", "서포트벡터머신.", "class-2"),
    ("7. 앙상블", "배부", "배(Bagging) · 부(Boosting)", "병렬 vs 순차 가중.", "ensemble-0"),
    ("8. 평가", "혼정재F1", "혼동행렬→Precision·Recall→F1", "분류 성능지표.", "eval-0"),
    ("8. ROC/PR", "TPR-FPR vs P-R", "균형→ROC / 불균형→PR", "곡선 선택 기준.", "eval-1"),
    ("9. RL", "상행보정", "상(태) · 행(동) · 보(상) · 정(책)", "강화학습 4요소.", "rl-0"),
    ("9. Q-learning", "Q-벨만-ε", "Q(s,a) 벨만·Off-policy·ε-greedy", "값기반 RL.", "rl-1"),
    ("10. DL", "입은출", "입(력) · 은(닉) · 출(력)", "ANN 3층 구조.", "dl-0"),
    ("10. 역전파", "순손역갱", "순전파→손실→역전파→가중치갱신", "Backpropagation.", "dl-2"),
    ("10. 활성화", "ReLU-Softmax", "은닉 ReLU · 다중분류 Softmax", "층별 활성화함수.", "dl-4"),
    ("11. CNN", "컨풀-풀-FC", "Convolution→Pooling→Fully Connected", "CNN 파이프라인.", "dl-cnn"),
    ("11. RNN/LSTM", "순환-게이트", "RNN 순환 · LSTM 3게이트", "시퀀스 모델.", "dl-rnn"),
    ("12. NLP", "RNN-Att-Trans", "RNN→Attention→Transformer", "NLP 아키텍처 진화.", "nlp-1"),
    ("12. LLM", "Pre-RLHF-FT", "Pretrain→RLHF→Fine-tuning", "ChatGPT 학습 3단.", "gen-2"),
    ("12. RAG", "검색-증강-생성", "Retrieve→Augment→Generate", "LLM 환각 완화.", "gen-3"),
    ("12. Foundation", "대규모-전이-파", "대규모·사전학습·파인튜닝", "Foundation Model.", "gen-4"),
]

SECTIONS = [
    {
        "id": "study",
        "title": "0. 기출 분석 및 공부 방식",
        "topics": [
            {
                "id": "study-0",
                "title": "AI 기술사 공부 방식",
                "pages": "교재 전체",
                "mnemonic": "키-도-표",
                "chips": ["키워드", "도식", "표", "기출연계"],
                "diagram": "① 기출 키워드 → ② 알고리즘·흐름도 → ③ 비교표 → ④ 윤리·적용·결론",
                "rows": [
                    ("키워드", "두음·영문약어·구성요소 나열", "ANI/AGI, RAG, PACELC급 비교, RL MDP"),
                    ("도식", "학습·추론·평가 흐름 복원", "지도/비지도, CNN층, Transformer, RL 루프"),
                    ("표", "알고리즘·지표·윤리 3열 표", "K-means vs DBSCAN, ROC vs PR, 3원칙 10요건"),
                    ("기출", "135~131회 AI 빈출 우선", "LLM·RAG·딥페이크·SVM·강화학습·XAI"),
                ],
                "depth": [
                    ("1·2교시 답안 틀", [
                        ("1교시", "정의→구성요소 표→비교 1개→결론", "30줄: ML/DL/생성형AI 개념형"),
                        ("2교시", "개요→핵심(표+절차)→적용→윤리·한계", "70줄: LLM 도입, RL, 딥페이크 대응"),
                        ("융합형", "통계+ML, 빅데이터+AI, 보안+생성형AI", "다중 분야 연결 답안"),
                    ]),
                ],
                "answer": "AI 과목은 개념 정의에 알고리즘 절차·평가지표·윤리·적용사례를 결합해야 하며, 최근 기출은 LLM·RAG·딥페이크·멀티모달·AI 거버넌스 비중이 높다.",
            },
        ],
    },
    {
        "id": "overview",
        "title": "1. 인공지능 개요",
        "topics": [
            {
                "id": "overview-0",
                "title": "AI 정의·연대표·3차 붐",
                "pages": "p.14~17, 23~24",
                "mnemonic": "1956 다트머스",
                "chips": ["정의", "AI 겨울", "전문가시스템", "딥러닝"],
                "diagram": "1950 튜링 → 1956 다트머스 → 1970 AI겨울 → 1980 전문가시스템 → 2010 ML/DL",
                "rows": [
                    ("정의", "인간 지능적 행동을 컴퓨터로 구현하는 IT 분야", "사전·전통·기술적 개념 3관점"),
                    ("3차 붐", "빅데이터 + GPU/HW + 알고리즘(딥러닝)", "데이터·연산·알고리즘 3요인"),
                    ("규칙→데이터", "규칙기반→지식기반→전문가시스템→ML/DL", "패러다임 전환"),
                ],
                "depth": [
                    ("AI 연대표", [
                        ("1950", "튜링 'Computing Machinery and Intelligence'", "지능 판별 논의"),
                        ("1956", "다트머스 워크샵 — AI학 탄생", "기호주의 시작"),
                        ("1970·1980", "1·2차 AI 겨울 — 기대 대비 성능·비용", "펀딩 삭감"),
                        ("2010~", "빅데이터·GPU·딥러닝 — 3차 붐", "ImageNet, AlphaGo"),
                    ]),
                ],
                "answer": "AI는 인간의 사고·학습을 컴퓨터로 구현하는 학문이며, 3차 붐은 빅데이터·하드웨어 성능·딥러닝 알고리즘의 convergence로 설명한다.",
            },
            {
                "id": "overview-1",
                "title": "ANI·AGI·ASI 분류",
                "pages": "p.18~19",
                "mnemonic": "약강초",
                "chips": ["ANI", "AGI", "ASI", "도메인특화", "범용"],
                "diagram": "ANI(특정업무) → AGI(인간급 범용) → ASI(초월)",
                "rows": [
                    ("ANI", "특정 도메인 최적화 — 음성인식·번역·AlphaFold", "현재 상용화, 위험 낮음"),
                    ("AGI", "인간 수준 다양한 작업·자율학습", "연구 중(GPT-4 등), 윤리·통제"),
                    ("ASI", "인간 초월·자기개선", "이론적, 매우 높은 위험"),
                ],
                "depth": [
                    ("ANI 필요성 (135회)", [
                        ("단계적 발전", "ANI 축적이 AGI/ASI 안전 연구 기반", "기술·윤리·규제 학습"),
                        ("실용성", "도메인별 검증·품질보증 가능", "산업 적용"),
                        ("리스크 관리", "범위 제한으로 통제 용이", "단계적 확장"),
                    ]),
                ],
                "answer": "ANI는 특정 기능에 특화된 현재 AI이며, AGI로 가기 위한 기술·윤리·거버넌스 학습의 필수 단계로 ANI의 안전한 축적이 강조된다.",
            },
            {
                "id": "overview-2",
                "title": "튜링테스트·CAPTCHA·규칙기반 진화",
                "pages": "p.21~22",
                "mnemonic": "5분 5회 1/3",
                "chips": ["튜링테스트", "CAPTCHA", "전문가시스템", "추천엔진"],
                "rows": [
                    ("튜링테스트", "5분 5회 대화 후 심판 1/3 속이면 통과", "지능 판별"),
                    ("CAPTCHA", "사람 vs 봇 구별 — 역튜링테스트", "보안"),
                    ("전문가시스템", "규칙+추론엔진 — MYCIN, Dendral", "IF-THEN, 퍼지논리"),
                    ("추천엔진", "협업필터링 기반 추측 제시", "Netflix, 쇼핑몰"),
                ],
                "answer": "튜링테스트는 기계 대화 지능 판별법이며, AI는 규칙기반에서 데이터 기반 ML/DL로 진화했다.",
            },
            {
                "id": "overview-3",
                "title": "AI 윤리·XAI·적대적공격·특이점",
                "pages": "p.20, 24~29",
                "mnemonic": "인공기 / 인프다침공연책안투",
                "chips": ["트롤리딜레마", "XAI", "Adversarial", "Singularity"],
                "diagram": "윤리 3원칙 → 10요건 / XAI: LIME·SHAP / 공격: Evasion·Poisoning·Backdoor",
                "rows": [
                    ("윤리 3원칙", "인간존엄·공공선·합목적성", "129회 기출"),
                    ("10대 요건", "인권·프라이버시·다양성·침해금지·공공·연대·데이터·책임·안전·투명", "표로 완전기재"),
                    ("XAI", "설명가능 AI — LIME, SHAP, Grad-CAM, Attention", "DARPA XAI 프로젝트"),
                    ("적대적공격", "Evasion·Poisoning·Model Extraction·Inversion·Backdoor", "적대적훈련·탐지·차단"),
                    ("특이점", "AI가 인간 지능 초월하는 시점", "규제·법규 필요성"),
                ],
                "depth": [
                    ("XAI 기법 분류", [
                        ("모델기반", "White-box, Interpretable NN, Surrogate", "DT·선형회귀"),
                        ("사후설명", "LIME, SHAP, Counterfactual", "블랙박스 설명"),
                        ("시각화", "Saliency Map, Grad-CAM", "CNN 설명"),
                    ]),
                ],
                "answer": "AI 윤리는 3대 원칙과 10대 요건으로 답안화하고, XAI는 LIME·SHAP 등으로 설명가능성을 확보하며, 적대적 공격 유형별 대응을 함께 기술한다.",
            },
        ],
    },
    {
        "id": "ml",
        "title": "2. 머신러닝 (ML)",
        "topics": [
            {
                "id": "ml-0",
                "title": "ML 개요·지도/비지도/강화학습",
                "pages": "p.31~40",
                "mnemonic": "지비강",
                "chips": ["Training Set", "Model", "Inference", "Label"],
                "diagram": "지도(Label O) | 비지도(Label X) | 강화(Reward)",
                "rows": [
                    ("ML 정의", "명시적 프로그래밍 없이 데이터로부터 학습", "Training·Model·Inference"),
                    ("지도학습", "Classification·Regression", "KNN, DT, SVM, RF, ANN"),
                    ("비지도학습", "Clustering·Dimension Reduction·Association", "K-means, PCA, Apriori"),
                    ("강화학습", "State-Action-Reward-Policy", "Q-learning, DQN, PPO"),
                ],
                "depth": [
                    ("파라미터 vs 하이퍼파라미터", [
                        ("Parameter", "학습으로 결정 — 가중치, μ, σ", "모델 능력"),
                        ("Hyperparameter", "사용자 설정 — learning rate, K", "튜닝 대상"),
                        ("학습절차", "입력→예측→손실→역전파→반복", "6단계"),
                    ]),
                ],
                "answer": "ML은 Label 유무에 따라 지도·비지도로 나뉘고 강화학습은 보상 최대화 정책을 학습한다.",
            },
            {
                "id": "ml-1",
                "title": "강화학습 — MDP·Q-learning·DQN",
                "pages": "p.39~40, 114~119",
                "mnemonic": "상행보정 / Q-벨만-ε",
                "chips": ["MDP", "Bellman", "Q-learning", "DQN", "MCTS"],
                "diagram": "Agent↔Environment: s→a→r→s' / Q(s,a)←r+γmaxQ(s',a')",
                "rows": [
                    ("구성요소", "Agent·Environment·State·Action·Reward·Policy·Q·γ", "6요소+α"),
                    ("Model-Free", "Policy-Based(PPO) vs Value-Based(Q-learning)", "On/Off-Policy"),
                    ("Q-learning", "Off-policy, Q-table, ε-greedy, Bellman", "114회"),
                    ("DQN", "DNN+Q, Replay Buffer, Target Network", "고차원 환경"),
                    ("MCTS", "Monte Carlo Tree Search — AlphaGo", "135·113회"),
                ],
                "depth": [
                    ("강화학습 분류", [
                        ("Policy-Based", "REINFORCE, PPO, DDPG", "연속 행동"),
                        ("Value-Based", "Q-learning, DQN, Double DQN", "Q값 근사"),
                        ("Actor-Critic", "A2C, A3C, SAC", "Policy+Value 혼합"),
                    ]),
                ],
                "answer": "강화학습은 MDP 위에서 보상을 최대화하는 정책을 학습하며, Q-learning은 Off-policy 값기반이고 DQN은 신경망으로 Q함수를 근사한다.",
            },
        ],
    },
    {
        "id": "cluster",
        "title": "3. 군집분석",
        "topics": [
            {
                "id": "cluster-0",
                "title": "K-means·계층적·GMM",
                "pages": "p.41~48",
                "mnemonic": "K-중심-반복",
                "chips": ["Centroid", "K", "Elbow", "Silhouette"],
                "diagram": "1)K선택 2)초기중심 3)할당 4)중심재계산 → 수렴",
                "rows": [
                    ("K-means", "K개 중심, 유클리드 거리 최소", "K·초기값·Elbow·Silhouette"),
                    ("계층적", "Agglomerative/Divisive, 덴드로그램", "군집 수 사후 결정"),
                    ("GMM", "가우시안 혼합, EM 알고리즘", "확률적 군집"),
                ],
                "answer": "K-means는 중심 기반 파티셔닝이며 K 선택은 Elbow·Silhouette(135회)로 판단한다.",
            },
            {
                "id": "cluster-1",
                "title": "DBSCAN·SOM",
                "pages": "p.49~57",
                "mnemonic": "밀도-코어-보더",
                "chips": ["ε", "MinPts", "Core", "Border", "Noise"],
                "rows": [
                    ("DBSCAN", "밀도 기반 — ε-neighborhood, MinPts", "임의 형상, 노이즈 검출"),
                    ("SOM", "Self-Organizing Map — 2D 격자 위치학습", "134회: NN과 차이"),
                    ("K vs DB", "K: 구형·K필요 / DB: 밀도·노이즈·ε", "129·130회 비교"),
                ],
                "answer": "DBSCAN은 밀도 기반으로 코어·보더·노이즈를 구분하며 K-means와 형상·K·노이즈 처리에서 차이난다.",
            },
        ],
    },
    {
        "id": "dim",
        "title": "4. 차원축소·오토인코더",
        "topics": [
            {
                "id": "dim-0",
                "title": "PCA·Autoencoder·차원의 저주",
                "pages": "p.58~64",
                "mnemonic": "공분산-고유값",
                "chips": ["PCA", "Autoencoder", "Curse of Dimensionality"],
                "rows": [
                    ("PCA", "공분산 행렬 고유값·주성분 투영", "선형 차원축소"),
                    ("Autoencoder", "Encoder→Latent→Decoder, 재구성 오차 최소", "131·135회 VAE"),
                    ("차원의 저주", "고차원에서 거리·샘플 희소·과적합", "135회, Grid Search 연계"),
                ],
                "answer": "PCA는 분산 보존 선형축소, Autoencoder/VAE는 비선형·생성형 표현학습이며 차원의 저주는 하이퍼파라미터 탐색 비용 증가로 연결된다.",
            },
        ],
    },
    {
        "id": "assoc",
        "title": "5. 연관규칙",
        "topics": [
            {
                "id": "assoc-0",
                "title": "Apriori·Support·Confidence·Lift",
                "pages": "p.65~71",
                "mnemonic": "지지-신뢰-향상",
                "chips": ["Apriori", "Support", "Confidence", "Lift"],
                "diagram": "Apriori: 빈발항목집→연관규칙 생성 / Support≥min, Confidence≥min",
                "rows": [
                    ("Support", "A∪B 동시 발생 비율", "빈도"),
                    ("Confidence", "P(B|A) — A일 때 B", "신뢰도"),
                    ("Lift", "Confidence/P(B) — 독립 대비", ">1 양의 연관"),
                    ("Apriori", "후보 생성·가지치기 — 하위집합 비빈발이면 상위도", "장바구니 분석"),
                ],
                "answer": "연관규칙은 Support·Confidence·Lift로 평가하며 Apriori는 빈발항목집 기반 후보 가지치기로 효율화한다.",
            },
        ],
    },
    {
        "id": "class",
        "title": "6. 분류·회귀",
        "topics": [
            {
                "id": "class-0",
                "title": "의사결정나무·KNN",
                "pages": "p.72~76",
                "mnemonic": "지니-엔트로피",
                "chips": ["Gini", "Entropy", "KNN", "Overfitting"],
                "rows": [
                    ("DT", "Gini·Entropy로 불순도 최소 분할", "126·130회"),
                    ("KNN", "K개 이웃 다수결·거리", "K 선택 중요"),
                    ("과적합", "깊은 트리·K 작음 → 과적합", "Pruning·K↑"),
                ],
                "answer": "DT는 Gini/Entropy로 분할하고 KNN은 K와 거리 척도가 성능을 좌우한다.",
            },
            {
                "id": "class-1",
                "title": "로지스틱회귀·선형회귀",
                "pages": "p.77~80, 120",
                "mnemonic": "로짓-Sigmoid",
                "chips": ["Logit", "Sigmoid", "MSE", "Homoscedasticity"],
                "rows": [
                    ("선형회귀", "Y=βX+ε, MSE 최소", "연속 예측"),
                    ("로지스틱", "로짓변환, Sigmoid, Cross-Entropy", "이진 분류"),
                    ("회귀 가정", "등분산성·다중공선성·선형성·독립성", "135·132회"),
                ],
                "answer": "로지스틱 회귀는 로짓변환으로 확률을 모델링하고 회귀는 등분산·다중공선성 가정 위반 시 진단·대응이 필요하다.",
            },
            {
                "id": "class-2",
                "title": "SVM",
                "pages": "p.81~89",
                "mnemonic": "마진-서포트",
                "chips": ["Margin", "Kernel", "Soft margin", "SV"],
                "rows": [
                    ("개념", "최대 마진 초평면, 서포트벡터", "132·119회"),
                    ("선형", "Hard/Soft margin — C 파라미터", "132회 마진 2가지"),
                    ("비선형", "Kernel trick — RBF, Polynomial", "고차원 매핑"),
                ],
                "answer": "SVM은 마진 최대화 분류기로 서포트벡터만 결정 경계에 영향을 주며 커널로 비선형 확장한다.",
            },
        ],
    },
    {
        "id": "valid",
        "title": "7. 검증·앙상블",
        "topics": [
            {
                "id": "valid-0",
                "title": "교차검증·과적합",
                "pages": "p.90~98",
                "mnemonic": "Train-Val-Test",
                "chips": ["K-Fold", "Hold-out", "Bias-Variance"],
                "rows": [
                    ("Hold-out", "Train/Validation/Test 분할", "128회 CV"),
                    ("K-Fold", "K번 분할·평균 성능", "데이터 효율"),
                    ("과적합", "Train↓ Test↑ — 편향·분산 Trade-off", "127·126회"),
                ],
                "answer": "교차검증은 일반화 성능 추정에 필수이며 과적합은 규제·Dropout·Early Stop·데이터 확보로 완화한다.",
            },
            {
                "id": "ensemble-0",
                "title": "Bagging·Boosting·Random Forest",
                "pages": "p.99~105",
                "mnemonic": "배부",
                "chips": ["Bagging", "Boosting", "RF", "AdaBoost", "XGBoost"],
                "diagram": "Bagging: 병렬 Bootstrap / Boosting: 순차 가중치↑",
                "rows": [
                    ("Bagging", "Bootstrap + 다수결 — RF", "분산 감소"),
                    ("Boosting", "오분류 가중 — AdaBoost, GBM, XGBoost", "편향 감소"),
                    ("RF", "Bagging + DT + Feature random", "110·126회"),
                ],
                "answer": "Bagging은 병렬 앙상블로 분산을, Boosting은 순차 학습으로 편향을 줄이며 RF는 Bagging+DT 조합이다.",
            },
        ],
    },
    {
        "id": "eval",
        "title": "8. 모델 평가",
        "topics": [
            {
                "id": "eval-0",
                "title": "혼동행렬·Precision·Recall·F1",
                "pages": "p.106~110",
                "mnemonic": "혼정재F1",
                "chips": ["TP", "FP", "FN", "TN", "F1"],
                "rows": [
                    ("Precision", "TP/(TP+FP) — 정밀도", "FP↓"),
                    ("Recall", "TP/(TP+FN) — 재현율·TPR", "FN↓"),
                    ("F1", "2PR/(P+R) — 조화평균", "116회"),
                    ("Accuracy", "(TP+TN)/Total — 불균형 시 부적절", "주의"),
                ],
                "answer": "혼동행렬에서 Precision·Recall·F1을 산출하며 불균형 데이터는 Accuracy 단독 사용을 피한다.",
            },
            {
                "id": "eval-1",
                "title": "ROC·PR 곡선",
                "pages": "p.111",
                "mnemonic": "TPR-FPR vs P-R",
                "chips": ["ROC", "AUC", "PR", "Threshold"],
                "rows": [
                    ("ROC", "TPR vs FPR, AUC — 균형 데이터", "135회 vs PR"),
                    ("PR", "Precision vs Recall — 불균형", "사기·희귀질병"),
                    ("AUC=0.5", "랜덤과 동일", "모델 무의미"),
                ],
                "answer": "균형 데이터는 ROC-AUC, 불균형(Positive 적음)은 PR 곡선이 적합하다(135회 비교).",
            },
        ],
    },
    {
        "id": "optimize",
        "title": "9. 최적화·하이퍼파라미터",
        "topics": [
            {
                "id": "optimize-0",
                "title": "경사하강법·Adam·하이퍼파라미터 튜닝",
                "pages": "p.120~128",
                "mnemonic": "Grid-Random-Bayes",
                "chips": ["SGD", "Adam", "Grid Search", "Bayesian Opt"],
                "rows": [
                    ("GD", "BGD·SGD·Mini-batch — 기울기 반대", "119·120회"),
                    ("Adam", "Momentum + RMSprop", "DL 기본 Optimizer"),
                    ("Grid Search", "전 조합 탐색 — 차원의 저주", "완전탐색"),
                    ("Random Search", "무작위 샘플 — 효율적", "고차원"),
                    ("Bayesian Opt", "GP + Acquisition Function", "132·131회"),
                ],
                "answer": "하이퍼파라미터는 Grid→Random→Bayesian 순으로 효율이 높아지며 Bayesian은 적은 시도로 최적에 근접한다.",
            },
        ],
    },
    {
        "id": "dl",
        "title": "10. 딥러닝 (DL)",
        "topics": [
            {
                "id": "dl-0",
                "title": "ML vs DL·ANN 구조",
                "pages": "p.129~131",
                "mnemonic": "입은출",
                "chips": ["DNN", "Feature Engineering", "GPU"],
                "rows": [
                    ("ML vs DL", "ML: 수동 특징 / DL: 자동 특징·대량 데이터·GPU", "131회"),
                    ("ANN", "입력·은닉·출력, Weight·Bias·Activation", "133회"),
                    ("구성", "Neuron·Loss·Backprop·Optimizer", "6요소"),
                ],
                "answer": "DL은 다층 신경망으로 특징을 자동 추출하며 GPU·빅데이터가 전제 조건이다.",
            },
            {
                "id": "dl-1",
                "title": "퍼셉트론·MLP·XOR",
                "pages": "p.133~137",
                "mnemonic": "단층-XOR불가",
                "chips": ["Perceptron", "ADALINE", "MLP", "XOR"],
                "rows": [
                    ("단층", "AND/OR 가능, XOR 불가", "113회"),
                    ("ADALINE", "연속 출력, LMS — Delta rule", "역전파 기초"),
                    ("MLP", "은닉층+역전파 → XOR 해결", "비선형"),
                ],
                "answer": "단층 퍼셉트론은 선형분리만 가능하고 MLP+역전파로 XOR 등 비선형 문제를 해결한다.",
            },
            {
                "id": "dl-2",
                "title": "역전파·Vanishing Gradient",
                "pages": "p.138~145",
                "mnemonic": "순손역갱",
                "chips": ["Backprop", "ReLU", "Dropout", "Batch Norm"],
                "rows": [
                    ("역전파", "순전파→손실→Chain Rule→가중치 갱신", "119·133회"),
                    ("Vanishing", "Sigmoid/Tanh 깊은층 기울기 소멸", "2차 AI 겨울 원인"),
                    ("해결", "ReLU·Batch Norm·Dropout·Pre-training", "145p"),
                ],
                "answer": "역전파는 Chain Rule로 손실을 역전파해 가중치를 갱신하며 Vanishing Gradient는 ReLU·Batch Norm 등으로 완화한다.",
            },
            {
                "id": "dl-3",
                "title": "과적합·규제화",
                "pages": "p.149~153",
                "mnemonic": "L1-L2-Drop-Early",
                "chips": ["L1", "L2", "Dropout", "Early Stopping"],
                "rows": [
                    ("Overfitting", "Train good·Test bad — 분산↑", "127회"),
                    ("L1/L2", "Lasso(희소)·Ridge(축소)", "Regularization"),
                    ("Dropout", "학습 시 뉴런 확률적 비활성", "앙상블 효과"),
                ],
                "answer": "과적합은 L1/L2·Dropout·Early Stopping·교차검증·데이터 확보로 대응한다.",
            },
            {
                "id": "dl-cnn",
                "title": "CNN",
                "pages": "p.155~159",
                "mnemonic": "컨풀-풀-FC",
                "chips": ["Convolution", "Pooling", "Padding", "Stride"],
                "diagram": "Input→Conv→Pool→Conv→Pool→Flatten→FC→Output",
                "rows": [
                    ("Conv", "Kernel·Stride·Padding·Feature Map", "128회 계층"),
                    ("Pooling", "Max/Avg — 차원축소·위치불변", "과적합 완화"),
                    ("FC", "Flatten→Dense→Softmax", "최종 분류"),
                    ("개선", "ResNet·DenseNet·EfficientNet", "Skip connection"),
                ],
                "answer": "CNN은 Conv로 국소 특징, Pooling으로 축소, FC로 분류하며 ResNet은 Skip connection으로 기울기 소실을 해결한다.",
            },
            {
                "id": "dl-rnn",
                "title": "RNN·LSTM·GRU·GAN",
                "pages": "p.160~166",
                "mnemonic": "순환-게이트",
                "chips": ["RNN", "LSTM", "GRU", "GAN", "BPTT"],
                "rows": [
                    ("RNN", "Hidden state 순환, BPTT — 장기의존성 문제", "120회"),
                    ("LSTM", "Forget·Input·Output Gate + Cell State", "3게이트"),
                    ("GRU", "Update·Reset — LSTM 경량화", "2게이트"),
                    ("GAN", "Generator vs Discriminator 적대학습", "DeepFake·이미지생성"),
                ],
                "answer": "RNN은 시퀀스 학습, LSTM/GRU는 게이트로 장기의존성을 해결하고 GAN은 생성자·판별자 경쟁으로 합성 데이터를 생성한다.",
            },
        ],
    },
    {
        "id": "platform",
        "title": "11. 플랫폼·딥페이크·LangChain",
        "topics": [
            {
                "id": "platform-0",
                "title": "TensorFlow·LangChain·딥페이크",
                "pages": "p.167~171",
                "mnemonic": "TF-Lang-Deep",
                "chips": ["TensorFlow", "LangChain", "Deepfake", "GAN"],
                "rows": [
                    ("TensorFlow", "Google E2E DL — Keras, TF Lite, TF.js", "그래프·Eager"),
                    ("LangChain", "LLM 앱 프레임워크 — Chain·Agent·VectorDB", "132회 예지정비"),
                    ("딥페이크", "GAN·Autoencoder·Neural Rendering", "133·135회"),
                    ("대응", "탐지AI·워터마킹·법규·디지털리터러시", "5대 대응"),
                ],
                "depth": [
                    ("딥페이크 탐지", [
                        ("영상", "CNN·Xception·프레임간 불일치", "Blink·PPG"),
                        ("음성", "MFCC·WaveNet", "음향 특성"),
                        ("메타", "EXIF·GAN artifact", "포렌식"),
                    ]),
                ],
                "answer": "LangChain은 LLM+VectorDB+Chain으로 RAG·에이전트 앱을 구축하고, 딥페이크는 GAN 기반이며 탐지·법규·교육으로 대응한다.",
            },
        ],
    },
    {
        "id": "nlp",
        "title": "12. NLP·Transformer·LLM",
        "topics": [
            {
                "id": "nlp-0",
                "title": "NLP 개요·NLU·NLG",
                "pages": "p.172~174",
                "mnemonic": "NLU-NLG",
                "chips": ["NLP", "NLU", "NLG", "Tokenization"],
                "rows": [
                    ("NLP", "자연어 이해·생성·처리", "비정형 텍스트"),
                    ("NLU", "의미·문맥 이해", "Intent·Entity"),
                    ("NLG", "데이터→자연어 생성", "요약·번역"),
                ],
                "answer": "NLP는 NLU(이해)와 NLG(생성)로 나뉘며 기계번역·챗봇·감성분석에 활용된다.",
            },
            {
                "id": "nlp-1",
                "title": "RNN→Attention→Transformer",
                "pages": "p.174~177",
                "mnemonic": "RNN-Att-Trans",
                "chips": ["Seq2Seq", "Attention", "Self-Attention", "Transformer"],
                "diagram": "RNN→LSTM→Seq2Seq+Att→Transformer(Encoder-Decoder)",
                "rows": [
                    ("Attention", "Query-Key-Value, Context vector 한계 해결", "175p"),
                    ("Self-Attention", "문장 내 단어 간 관계 — Q·K·V", "병렬 연산"),
                    ("Transformer", "Multi-Head·FFN·Positional Encoding", "RNN 제거"),
                ],
                "answer": "Transformer는 Self-Attention으로 장거리 의존성을 병렬 학습하며 GPT·BERT의 기반이다.",
            },
            {
                "id": "gen-0",
                "title": "생성형 AI·판별 vs 생성 모델",
                "pages": "p.180~183",
                "mnemonic": "판별-생성",
                "chips": ["Generative", "Discriminative", "GAN", "VAE"],
                "rows": [
                    ("판별모델", "P(Y|X) — SVM, LR", "경계 학습"),
                    ("생성모델", "P(X) 또는 P(X|Y) — GAN, VAE", "데이터 생성"),
                    ("Explicit/Implicit", "VAE(명시적) vs GAN(암시적)", "밀도 추정"),
                ],
                "answer": "생성형 AI는 데이터 분포를 학습해 새 샘플을 생성하며 GAN·VAE·Diffusion이 대표적이다.",
            },
            {
                "id": "gen-1",
                "title": "GPT·ChatGPT 학습·RLHF",
                "pages": "p.178~179",
                "mnemonic": "Pre-RLHF-FT",
                "chips": ["GPT", "RLHF", "PPO", "Fine-tuning"],
                "diagram": "Pretrain→Supervised FT→Reward Model→PPO(RLHF)",
                "rows": [
                    ("Pretraining", "대규모 텍스트, Transformer Decoder", "Next token prediction"),
                    ("RLHF", "Human Feedback + PPO", "대화 최적화"),
                    ("Fine-tuning", "Task-specific — QA·코드·번역", "132회 Fine-tuning"),
                ],
                "answer": "ChatGPT는 Pretraining 후 RLHF(PPO)로 인간 선호를 반영하고 Task별 Fine-tuning으로 특화한다.",
            },
            {
                "id": "gen-2",
                "title": "LLM·Foundation Model·RAG",
                "pages": "p.180~193",
                "mnemonic": "검색-증강-생성",
                "chips": ["LLM", "Foundation Model", "RAG", "Prompt Engineering"],
                "rows": [
                    ("Foundation Model", "대규모 사전학습·전이·파인튜닝", "131·135회"),
                    ("LLM", "수십억~조 parameter — GPT, LLaMA, Claude", "135회 5고려·5아키텍처"),
                    ("RAG", "Retrieve+Augment+Generate — VectorDB", "135·134·132회"),
                    ("Prompt Engineering", "Few-shot·CoT·Role — 135회", "할루시네이션 완화"),
                ],
                "depth": [
                    ("LLM 적용 5고려 (135회)", [
                        ("데이터", "품질·보안·저작권", "학습 데이터"),
                        ("인프라", "GPU·클라우드·비용", "추론 지연"),
                        ("윤리", "편향·환각·프라이버시", "거버넌스"),
                        ("통합", "RAG·Fine-tuning·API", "아키텍처"),
                        ("운영", "모니터링·버전·MLOps", "지속 개선"),
                    ]),
                ],
                "answer": "Foundation Model/LLM은 사전학습+Fine-tuning/RAG로 도메인 적용하며, RAG는 외부 지식 검색으로 환각을 줄인다.",
            },
            {
                "id": "gen-3",
                "title": "멀티모달·초거대AI·온디바이스",
                "pages": "p.134, 167",
                "mnemonic": "텍스트-이미지-음성",
                "chips": ["Multimodal", "Super-Giant AI", "On-device AI"],
                "rows": [
                    ("Multimodal", "텍스트+이미지+음성 통합 — GPT-4V", "134·135회"),
                    ("초거대AI", "공공 가이드라인 — 도입원칙·사전고려", "134회"),
                    ("On-device AI", "엣지 추론 — NPU·경량모델", "134·127회"),
                ],
                "answer": "멀티모달 LLM은 다중 입력을 통합 처리하고, 온디바이스 AI는 프라이버시·지연·오프라인을 위해 엣지에서 추론한다.",
            },
        ],
    },
]

FLASHCARDS = [
    ("AI개요", "ANI·AGI·ASI 차이?", "ANI: 특정도메인(현재상용)\nAGI: 인간급 범용(연구중)\nASI: 초월(이론적)"),
    ("AI개요", "AI 윤리 3대 원칙?", "① 인간존엄성 ② 공공선 ③ 합목적성\n+ 10대 핵심요건"),
    ("AI개요", "튜링테스트 통과 조건?", "5분 5회 대화\n심판 1/3 이상 속이면 통과"),
    ("ML", "지도/비지도/강화 차이?", "지도: Label O (분류·회귀)\n비지도: Label X (군집·PCA)\n강화: Reward (정책학습)"),
    ("ML", "파라미터 vs 하이퍼파라미터?", "Parameter: 학습으로 결정(가중치)\nHyperparameter: 사용자 설정(lr, K)"),
    ("군집", "K-means vs DBSCAN?", "K-means: K필요·구형\nDBSCAN: ε·MinPts·밀도·노이즈"),
    ("군집", "Silhouette Coefficient?", "군집 품질 — -1~1\n1에 가까울수록 잘 분리"),
    ("차원", "차원의 저주?", "고차원→거리 희석·과적합·탐색비용↑"),
    ("연관", "Support·Confidence·Lift?", "Support=P(A∪B)\nConfidence=P(B|A)\nLift=Conf/P(B)"),
    ("분류", "Gini vs Entropy?", "불순도 측정 — 0=순수\nDT 분할 기준"),
    ("분류", "SVM 핵심?", "최대 Margin 초평면\n서포트벡터만 경계 결정\nKernel→비선형"),
    ("앙상블", "Bagging vs Boosting?", "Bagging: 병렬 Bootstrap(RF)\nBoosting: 순차 오분류 가중"),
    ("평가", "Precision·Recall·F1?", "P=TP/(TP+FP)\nR=TP/(TP+FN)\nF1=2PR/(P+R)"),
    ("평가", "ROC vs PR?", "ROC: TPR vs FPR (균형)\nPR: P vs R (불균형)"),
    ("RL", "Q-learning 특징?", "Off-policy, Value-based\nQ(s,a)←r+γmaxQ(s',a')\nε-greedy"),
    ("RL", "Q-learning vs DQN?", "Q: Q-table, 작은 상태공간\nDQN: DNN+Replay+Target"),
    ("RL", "MDP 5요소?", "State·Action·Reward·Transition·Policy"),
    ("DL", "ML vs DL?", "ML: 수동 Feature·적은 데이터\nDL: 자동 Feature·GPU·Big Data"),
    ("DL", "단층 퍼셉트론 XOR?", "선형분리만 가능→XOR 불가\nMLP+은닉층+역전파로 해결"),
    ("DL", "Vanishing Gradient 해결?", "ReLU·Batch Norm·Dropout\nPre-training·Weight Init"),
    ("DL", "과적합 해결?", "L1/L2·Dropout·Early Stop\nCV·데이터 확보·차원축소"),
    ("CNN", "CNN 3계층?", "Conv(특징추출)→Pool(축소)→FC(분류)"),
    ("RNN", "LSTM 3 Gate?", "Forget·Input·Output\nCell State로 장기기억"),
    ("GAN", "GAN 구조?", "Generator(가짜생성)\nDiscriminator(진위판별)\n적대학습"),
    ("NLP", "Self-Attention QKV?", "Query·Key·Value\n내적→Softmax→가중합"),
    ("LLM", "ChatGPT 학습 3단?", "Pretrain→RLHF(PPO)→Fine-tuning"),
    ("LLM", "RAG 3단?", "Retrieve(검색)→Augment(컨텍스트)→Generate"),
    ("LLM", "Foundation Model?", "대규모 사전학습\n전이·파인튜닝·다운스트림"),
    ("윤리", "적대적 공격 5유형?", "Evasion·Poisoning·Extraction\nInversion·Backdoor"),
    ("XAI", "LIME vs SHAP?", "LIME: 국소 근사\nSHAP: Shapley 기여도"),
    ("딥페이크", "딥페이크 핵심기술?", "GAN·Autoencoder·Neural Rendering\n탐지·법규·리터러시"),
    ("최적화", "Grid vs Random vs Bayesian?", "Grid: 전조합(비용↑)\nRandom: 샘플링\nBayesian: GP+효율탐색"),
]

PAST_EXAMS_NOTE = "135~108회 AI 관련 기출을 교재 p.4~13 목차와 함께 정리했습니다. LLM·RAG·딥페이크·SVM·강화학습·XAI 빈출."
